# Generated by Django 4.1.4 on 2023-01-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_friends_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_request',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
